# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.btnRed = QtWidgets.QPushButton(self.centralwidget)
        self.btnRed.setObjectName("btnRed")
        self.gridLayout.addWidget(self.btnRed, 2, 5, 1, 1)
        self.btnArchive = QtWidgets.QPushButton(self.centralwidget)
        self.btnArchive.setObjectName("btnArchive")
        self.gridLayout.addWidget(self.btnArchive, 1, 5, 1, 1)
        self.inputWidth = QtWidgets.QLineEdit(self.centralwidget)
        self.inputWidth.setObjectName("inputWidth")
        self.gridLayout.addWidget(self.inputWidth, 2, 1, 1, 1)
        self.inputHeigth = QtWidgets.QLineEdit(self.centralwidget)
        self.inputHeigth.setObjectName("inputHeigth")
        self.gridLayout.addWidget(self.inputHeigth, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 434, 308))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblImage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.gridLayout_2.addWidget(self.lblImage, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 6)
        self.inputArchive = QtWidgets.QLineEdit(self.centralwidget)
        self.inputArchive.setObjectName("inputArchive")
        self.gridLayout.addWidget(self.inputArchive, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimensionar Imagem"))
        self.btnSave.setText(_translate("MainWindow", "Salvar"))
        self.label_2.setText(_translate("MainWindow", "Altura"))
        self.btnRed.setText(_translate("MainWindow", "Redimensionar"))
        self.btnArchive.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.label.setText(_translate("MainWindow", "Largura"))
